const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('offerManager', {
  getSnapshot: () => ipcRenderer.invoke('data:snapshot'),
  saveApplication: input => ipcRenderer.invoke('application:save', input),
  updateApplicationStatus: input => ipcRenderer.invoke('application:status', input),
  deleteApplication: id => ipcRenderer.invoke('application:delete', id),
  saveEvent: input => ipcRenderer.invoke('event:save', input),
  deleteEvent: id => ipcRenderer.invoke('event:delete', id),
  createReview: input => ipcRenderer.invoke('review:create', input),
  linkReview: input => ipcRenderer.invoke('review:link', input),
  readReview: id => ipcRenderer.invoke('review:read', id),
  saveReview: input => ipcRenderer.invoke('review:save', input),
  openReviewExternal: id => ipcRenderer.invoke('review:openExternal', id),
  deleteReview: id => ipcRenderer.invoke('review:delete', id),
  openUrl: url => ipcRenderer.invoke('system:openUrl', url),
  showDataFolder: () => ipcRenderer.invoke('system:showData'),
  exportCsv: () => ipcRenderer.invoke('data:exportCsv'),
  listOpportunities: () => ipcRenderer.invoke('opportunity:list'),
  chooseOpportunityImage: () => ipcRenderer.invoke('opportunity:chooseImage'),
  saveOpportunity: input => ipcRenderer.invoke('opportunity:save', input),
  toggleOpportunityApplied: input => ipcRenderer.invoke('opportunity:toggleApplied', input),
  deleteOpportunity: id => ipcRenderer.invoke('opportunity:delete', id),
  openOpportunityImage: id => ipcRenderer.invoke('opportunity:openImage', id),
  readOpportunityImage: id => ipcRenderer.invoke('opportunity:readImage', id),
})
